/**
 * ByokCodexHome — generates a self-contained `CODEX_HOME` for a BYOK instance.
 *
 * Codex is configured entirely through files, so pointing it at a
 * third-party provider means writing two of them:
 *
 *   - `config.toml`  — the `[model_providers.<id>]` block (endpoint, wire
 *     protocol, which env var holds the key) plus the active model.
 *   - `models.json`  — the model catalog. Without it an unknown slug inherits
 *     whichever flagship OpenAI model Codex ships with, so the picker
 *     advertises that model's reasoning levels and an OpenAI "Service Tier"
 *     row the provider does not have.
 *
 * Studio owns this directory: it is regenerated on every instance start and
 * lives under the server state dir, keyed by instance id, so two BYOK
 * instances (say DeepSeek and Kimi) never share provider config. Users are
 * not expected to hand-edit it.
 *
 * The API key is deliberately absent from everything written here. Codex's
 * own schema calls its inline `experimental_bearer_token` discouraged in
 * favour of `env_key`, so the generated config names an environment
 * variable and Studio injects the value from its secret store at spawn time.
 *
 * Two behaviors were measured against Codex 0.146.0 and are load-bearing:
 *
 *   1. `base_instructions` is required by the catalog schema but **ignored**
 *      on the third-party path — Codex sends its own built-in agent prompt.
 *      We still write something usable rather than a placeholder, so that a
 *      future Codex which does honor the field degrades instead of breaking.
 *   2. `input_modalities` does **not** gate attachments. Declaring a model
 *      text-only keeps the metadata honest but does not stop an image from
 *      being sent; blocking that is Studio's job, not the harness's.
 *
 * @module provider/Drivers/Byok/byokCodexHome
 */
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import type * as PlatformError from "effect/PlatformError";
import * as Schema from "effect/Schema";

import type { ByokPreset, ByokPresetModel, ByokReasoningEffort } from "./byokPresets.ts";

export const BYOK_CONFIG_FILE_NAME = "config.toml";
export const BYOK_CATALOG_FILE_NAME = "models.json";

/**
 * Written into every generated catalog entry. Never reaches the provider on
 * the paths we support today (see module docs) — this exists so the field is
 * meaningful rather than a stub if that ever changes.
 */
const FALLBACK_BASE_INSTRUCTIONS = [
  "You are a coding agent running in a terminal-based coding assistant.",
  "You share a workspace with the user and act on it directly.",
  "",
  "- Prefer reading files before editing them.",
  "- Make the smallest change that accomplishes the task.",
  "- Run the project's own tests and checks when they are available.",
  "- Report what you changed plainly, including anything you could not finish.",
].join("\n");

const EFFORT_DESCRIPTIONS: Record<ByokReasoningEffort, string> = {
  none: "No reasoning",
  minimal: "Minimal reasoning",
  low: "Fast responses with lighter reasoning",
  medium: "Balanced reasoning",
  high: "Deeper reasoning for complex work",
  xhigh: "Extended reasoning",
  max: "Maximum reasoning effort",
};

/**
 * Escape a string for a TOML basic (double-quoted) value. Windows paths make
 * backslash handling mandatory, not decorative.
 */
export function toTomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

export interface ByokCodexHomeInput {
  readonly preset: ByokPreset;
  /**
   * Models to write into the catalog. Passed in rather than read off the
   * preset because a routed provider resolves its lineup at runtime; for a
   * static preset this is simply `preset.models`.
   */
  readonly models: ReadonlyArray<ByokPresetModel>;
  /** Slug selected as this instance's active model. */
  readonly modelSlug: string;
  /** Absolute path of the generated catalog; Codex requires it absolute. */
  readonly catalogPath: string;
}

export function buildCodexConfigToml(input: ByokCodexHomeInput): string {
  const { preset, models, modelSlug, catalogPath } = input;
  const model = models.find((candidate) => candidate.slug === modelSlug);
  const providerId = preset.id;

  const lines = [
    "# Generated by Toolport Studio. Edits are overwritten on instance start.",
    `# Provider: ${preset.label} (${preset.wireFormat} wire protocol)`,
    "#",
    "# The API key is not stored here. Studio keeps it in its secret store and",
    `# injects it as ${preset.envKey} when launching this provider.`,
    "",
    `model = ${toTomlString(modelSlug)}`,
    `model_provider = ${toTomlString(providerId)}`,
    "",
    "# Never fall back to an interactive ChatGPT login: Studio drives Codex",
    "# non-interactively, so a login prompt would read as a hang.",
    'forced_login_method = "api"',
    "",
    "# Real capability metadata, replacing Codex's generic fallback. Read at",
    "# startup only, so the instance must restart for changes to apply.",
    `model_catalog_json = ${toTomlString(catalogPath)}`,
  ];

  if (model?.defaultReasoningEffort) {
    lines.push(
      "",
      "# Starting effort. The per-turn selection in Studio overrides this.",
      `model_reasoning_effort = ${toTomlString(model.defaultReasoningEffort)}`,
    );
  }

  lines.push(
    "",
    `[model_providers.${providerId}]`,
    `name = ${toTomlString(preset.label)}`,
    `base_url = ${toTomlString(preset.baseUrl)}`,
    `wire_api = ${toTomlString(preset.wireFormat)}`,
    `env_key = ${toTomlString(preset.envKey)}`,
    `env_key_instructions = ${toTomlString(
      `Create an API key at ${preset.apiKeysUrl}, then add ${preset.envKey} as a sensitive environment variable on this provider instance in Toolport Studio.`,
    )}`,
    "request_max_retries = 4",
    "stream_max_retries = 5",
    "stream_idle_timeout_ms = 300000",
    "",
    // Identifies the client to the provider. OpenRouter attributes requests
    // to it on their public leaderboards; nobody else reads it, and it
    // carries nothing about the user or the workspace.
    "[model_providers." + providerId + ".http_headers]",
    'X-Title = "Toolport Studio"',
    "",
  );

  return lines.join("\n");
}

/**
 * One entry of Codex's `ModelsResponse`. Deliberately typed loosely: the
 * shape belongs to Codex, tracks its releases, and unknown fields are
 * ignored on parse while missing required ones are fatal.
 */
type CodexCatalogEntry = Record<string, unknown>;

/**
 * Serializer for the catalog file. The value side stays `Unknown` because
 * the schema of record is Codex's Rust struct, not ours — pinning it here
 * would mean re-deriving it on every Codex release for no safety we can
 * actually enforce.
 */
const CodexModelCatalogJson = Schema.fromJsonString(
  Schema.Struct({ models: Schema.Array(Schema.Unknown) }),
);
const encodeCodexModelCatalog = Schema.encodeSync(CodexModelCatalogJson);

function buildCatalogEntry(model: ByokPresetModel, priority: number): CodexCatalogEntry {
  const efforts = model.reasoningEfforts.map((effort) => ({
    effort,
    description: EFFORT_DESCRIPTIONS[effort],
  }));

  return {
    slug: model.slug,
    display_name: model.displayName,
    description: model.description,
    ...(model.defaultReasoningEffort
      ? { default_reasoning_level: model.defaultReasoningEffort }
      : {}),
    supported_reasoning_levels: efforts,
    shell_type: "shell_command",
    visibility: "list",
    supported_in_api: true,
    priority,
    // Speed/service tiers are an OpenAI billing concept. Leaving these empty
    // is what removes the phantom "Service Tier" row from the model picker.
    additional_speed_tiers: [],
    service_tiers: [],
    availability_nux: null,
    upgrade: null,
    base_instructions: FALLBACK_BASE_INSTRUCTIONS,
    include_skills_usage_instructions: false,
    // Summaries are accepted by some providers but produce nothing, so don't
    // spend tokens asking for them.
    supports_reasoning_summary_parameter: false,
    default_reasoning_summary: "none",
    // `text.verbosity` is OpenAI-only.
    support_verbosity: false,
    default_verbosity: null,
    apply_patch_tool_type: model.supportsApplyPatch ? "freeform" : null,
    web_search_tool_type: model.supportsVision ? "text_and_image" : "text",
    supports_search_tool: model.supportsWebSearch,
    truncation_policy: { mode: "tokens", limit: 10_000 },
    supports_parallel_tool_calls: model.supportsParallelToolCalls,
    supports_image_detail_original: model.supportsVision,
    context_window: model.contextWindow,
    max_context_window: model.contextWindow,
    effective_context_window_percent: 95,
    experimental_supported_tools: [],
    input_modalities: model.supportsVision ? ["text", "image"] : ["text"],
    use_responses_lite: false,
  };
}

export function buildCodexModelCatalog(models: ReadonlyArray<ByokPresetModel>): {
  readonly models: ReadonlyArray<CodexCatalogEntry>;
} {
  return {
    models: models.map((model, index) => buildCatalogEntry(model, index + 1)),
  };
}

export interface MaterializedByokHome {
  readonly homePath: string;
  readonly configPath: string;
  readonly catalogPath: string;
}

/**
 * Write `config.toml` + `models.json` into `homePath`, creating it if
 * needed. Idempotent: regenerating over an existing home replaces both files
 * and leaves everything else (sessions, logs, the `[projects]` trust entries
 * Codex writes itself) alone.
 *
 * Note that the trust entries Codex appends to `config.toml` are lost on
 * regeneration, which only costs a re-trust prompt.
 */
export const materializeByokCodexHome = Effect.fn("materializeByokCodexHome")(function* (input: {
  readonly homePath: string;
  readonly preset: ByokPreset;
  readonly models: ReadonlyArray<ByokPresetModel>;
  readonly modelSlug: string;
}): Effect.fn.Return<
  MaterializedByokHome,
  PlatformError.PlatformError,
  FileSystem.FileSystem | Path.Path
> {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const homePath = path.resolve(input.homePath);
  const catalogPath = path.join(homePath, BYOK_CATALOG_FILE_NAME);
  const configPath = path.join(homePath, BYOK_CONFIG_FILE_NAME);

  yield* fileSystem.makeDirectory(homePath, { recursive: true });
  yield* fileSystem.writeFileString(
    catalogPath,
    `${encodeCodexModelCatalog(buildCodexModelCatalog(input.models))}\n`,
  );
  yield* fileSystem.writeFileString(
    configPath,
    buildCodexConfigToml({
      preset: input.preset,
      models: input.models,
      modelSlug: input.modelSlug,
      catalogPath,
    }),
  );

  return { homePath, configPath, catalogPath };
});
